// Generates seed/seed.sql: RBAC roles/permissions/role_permissions (mirrors
// packages/shared/src/{enums,permissions}.ts -- keep these in sync if that
// file changes) plus one bootstrap SUPER_ADMIN account and a starter set of
// master data reference rows so a freshly migrated database is immediately
// usable end-to-end, not just schema-complete.
//
// Run with: node scripts/generate-seed.mjs > seed/seed.sql
// (or `npm run db:generate-seed`, which pipes it there for you)

import { pbkdf2Sync, randomBytes, randomUUID } from "node:crypto";

const ROLE_LABELS = {
  SUPER_ADMIN: "Super Admin / IT Administrator",
  ADMIN_JASPEL: "Admin Jaspel / Tim Remunerasi",
  VERIFIKATOR_UNIT: "Verifikator Unit / Kepala Instalasi",
  KEUANGAN: "Bagian Keuangan / Pejabat Keuangan BLUD",
  DIREKTUR: "Direktur / Pejabat Pengelola BLUD",
  PEGAWAI: "Pegawai",
  AUDITOR: "Auditor / Inspektorat",
};

const ALL_PERMISSIONS = [
  "master.employee.read", "master.employee.write",
  "master.work_unit.read", "master.work_unit.write",
  "master.proportion_scheme.read", "master.proportion_scheme.write",
  "master.job_grade.read", "master.job_grade.write",
  "master.deduction_rule.read", "master.deduction_rule.write",
  "master.tariff.read", "master.tariff.write",
  "import.upload", "import.commit", "import.read",
  "calculation.run", "calculation.simulate", "calculation.read",
  "workflow.manage_period", "workflow.verify_unit", "workflow.verify_keuangan",
  "workflow.approve_direktur", "workflow.lock", "workflow.correction", "workflow.read",
  "self.dashboard.read", "self.slip.download",
  "dashboard.management.read",
  "report.export",
  "user.read", "user.write", "role.read", "role.write",
  "audit.read",
];

const DEFAULT_ROLE_PERMISSIONS = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  ADMIN_JASPEL: [
    "master.employee.read", "master.employee.write", "master.work_unit.read", "master.work_unit.write",
    "master.proportion_scheme.read", "master.proportion_scheme.write", "master.job_grade.read", "master.job_grade.write",
    "master.deduction_rule.read", "master.deduction_rule.write", "master.tariff.read", "master.tariff.write",
    "import.upload", "import.commit", "import.read",
    "calculation.run", "calculation.simulate", "calculation.read",
    "workflow.manage_period", "workflow.read", "workflow.correction",
    "report.export", "audit.read",
  ],
  VERIFIKATOR_UNIT: ["master.employee.read", "master.work_unit.read", "calculation.read", "workflow.verify_unit", "workflow.read", "report.export"],
  KEUANGAN: ["master.employee.read", "master.work_unit.read", "calculation.read", "workflow.verify_keuangan", "workflow.read", "dashboard.management.read", "report.export"],
  DIREKTUR: ["master.employee.read", "master.work_unit.read", "calculation.read", "workflow.approve_direktur", "workflow.read", "dashboard.management.read", "report.export", "audit.read"],
  PEGAWAI: ["self.dashboard.read", "self.slip.download"],
  AUDITOR: ["master.employee.read", "master.work_unit.read", "master.proportion_scheme.read", "master.job_grade.read", "master.deduction_rule.read", "master.tariff.read", "import.read", "calculation.read", "workflow.read", "dashboard.management.read", "audit.read"],
};

function hashPassword(password) {
  const iterations = 210_000;
  const salt = randomBytes(16);
  const hash = pbkdf2Sync(password, salt, iterations, 32, "sha256");
  return `pbkdf2$${iterations}$${salt.toString("base64")}$${hash.toString("base64")}`;
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

const lines = [];
lines.push("-- Generated by scripts/generate-seed.mjs. Do not hand-edit RBAC rows below;");
lines.push("-- re-run the generator instead. Master data rows below the marker are safe to extend by hand.");
lines.push("");

for (const [code, name] of Object.entries(ROLE_LABELS)) {
  lines.push(`INSERT OR IGNORE INTO roles (code, name) VALUES (${sqlString(code)}, ${sqlString(name)});`);
}
lines.push("");

for (const code of ALL_PERMISSIONS) {
  lines.push(`INSERT OR IGNORE INTO permissions (code) VALUES (${sqlString(code)});`);
}
lines.push("");

for (const [role, perms] of Object.entries(DEFAULT_ROLE_PERMISSIONS)) {
  for (const perm of perms) {
    lines.push(`INSERT OR IGNORE INTO role_permissions (role_code, permission_code) VALUES (${sqlString(role)}, ${sqlString(perm)});`);
  }
}
lines.push("");

const adminId = randomUUID();
const adminEmail = process.env.SEED_ADMIN_EMAIL ?? "admin@rsudlembang.go.id";
const adminPassword = process.env.SEED_ADMIN_PASSWORD ?? "GantiSegera#2026";
lines.push("-- Bootstrap Super Admin. CHANGE THIS PASSWORD IMMEDIATELY AFTER FIRST LOGIN.");
lines.push(`-- email: ${adminEmail}  temporary password: ${adminPassword}`);
lines.push(
  `INSERT OR IGNORE INTO users (id, email, password_hash, full_name, role_code, must_change_password) VALUES (${sqlString(adminId)}, ${sqlString(adminEmail)}, ${sqlString(hashPassword(adminPassword))}, ${sqlString("Super Administrator")}, 'SUPER_ADMIN', 1);`,
);
lines.push("");

// Starter master data so demo/staging environments aren't an empty shell.
const units = [
  ["RJ-01", "Rawat Jalan", "RAWAT_JALAN"],
  ["RI-01", "Rawat Inap", "RAWAT_INAP"],
  ["IGD-01", "Instalasi Gawat Darurat", "IGD"],
  ["IBS-01", "Instalasi Bedah Sentral", "IBS"],
  ["RAD-01", "Radiologi", "RADIOLOGI"],
  ["LAB-01", "Laboratorium Patologi Klinik", "LABORATORIUM_PATOLOGI_KLINIK"],
];
const unitIds = {};
for (const [code, name, category] of units) {
  const id = randomUUID();
  unitIds[code] = id;
  lines.push(
    `INSERT OR IGNORE INTO work_units (id, code, name, service_category) VALUES (${sqlString(id)}, ${sqlString(code)}, ${sqlString(name)}, ${sqlString(category)});`,
  );
}
lines.push("");

const grades = [
  ["JG-1", "Terampil", 10000],
  ["JG-2", "Mahir", 13000],
  ["JG-3", "Penyelia", 16000],
];
for (const [code, name, weightBp] of grades) {
  lines.push(
    `INSERT OR IGNORE INTO job_grades (id, code, name, weight_bp) VALUES (${sqlString(randomUUID())}, ${sqlString(code)}, ${sqlString(name)}, ${weightBp});`,
  );
}
lines.push("");

// Proportion scheme starter rows using the midpoint of each PRD table 9.1
// national reference range -- flagged for RSUD Lembang management to
// confirm/replace via the Master Skema Proporsi screen before go-live.
const proportionSeed = [
  ["RAWAT_INAP", "JKN", null, 1250],
  ["RAWAT_INAP", "NON_JKN", null, 6000],
  ["RAWAT_JALAN", "JKN", null, 1750],
  ["RAWAT_JALAN", "NON_JKN", null, 6000],
  ["IGD", "NON_JKN", null, 6000],
  ["IBS", "JKN", "OPERATOR", 1250],
  ["IBS", "NON_JKN", "OPERATOR", 2500],
  ["IBS", "JKN", "CO_OPERATOR", 700],
  ["IBS", "NON_JKN", "CO_OPERATOR", 650],
  ["IBS", "JKN", "ANESTESI", 450],
  ["IBS", "NON_JKN", "ANESTESI", 1050],
  ["RADIOLOGI", "JKN", null, 750],
  ["RADIOLOGI", "NON_JKN", null, 1250],
  ["LABORATORIUM_PATOLOGI_KLINIK", "JKN", null, 300],
  ["LABORATORIUM_PATOLOGI_KLINIK", "NON_JKN", null, 650],
];
for (const [category, penjaminan, role, bp] of proportionSeed) {
  lines.push(
    `INSERT OR IGNORE INTO proportion_schemes (id, service_category, penjaminan_status, service_role, percent_bp, effective_from, created_by, notes) VALUES (${sqlString(randomUUID())}, ${sqlString(category)}, ${sqlString(penjaminan)}, ${role ? sqlString(role) : "NULL"}, ${bp}, '2026-01-01', ${sqlString(adminId)}, ${sqlString("Seed: titik tengah rentang acuan Kepdirjen Yankes No. HK.02.02/D/286/2025 -- konfirmasi nilai final RSUD Lembang")});`,
  );
}
lines.push("");

const deductionSeed = [
  ["CUTI_GE_1_BULAN", "Cuti >= 1 bulan", 5000],
  ["PERKELAHIAN", "Terlibat perkelahian (masa pembinaan)", 5000],
  ["DIKLAT_GT_1_BULAN", "Diklat > 1 bulan", 5000],
  ["TUGAS_BELAJAR", "Tugas belajar, ketidakhadiran >= 3 hari/minggu", 8000],
];
for (const [code, name, bp] of deductionSeed) {
  lines.push(
    `INSERT OR IGNORE INTO deduction_rules (id, code, name, percent_bp, effective_from) VALUES (${sqlString(randomUUID())}, ${sqlString(code)}, ${sqlString(name)}, ${bp}, '2026-01-01');`,
  );
}
lines.push("");

const indexingSeed = [
  ["PENGALAMAN_MASA_KERJA", 1500, 100],
  ["KETERAMPILAN", 1500, 100],
  ["RISIKO_KERJA", 1500, 100],
  ["KEGAWATDARURATAN", 1500, 100],
  ["JABATAN", 2000, 100],
  ["CAPAIAN_KINERJA", 2000, 100],
];
for (const [variable, weightBp, maxScore] of indexingSeed) {
  lines.push(
    `INSERT OR IGNORE INTO indexing_weights (id, variable, weight_bp, max_score, effective_from) VALUES (${sqlString(randomUUID())}, ${sqlString(variable)}, ${weightBp}, ${maxScore}, '2026-01-01');`,
  );
}

process.stdout.write(lines.join("\n") + "\n");
